/*
!!! ATTENTION !!!
THIS FILE HAS BEEN AUTO-GENERATED
DO NOT EDIT THIS FILE
*/

// Imports 
import { AppConfig, api as axios } from '@/config/livestock-config'; 
import { ApiService } from '@/services/ApiService';

// Custom Types 
type Guid = string; 
type Double = number;
type Decimal = number;
type Int64 = number;
type Int32 = number;
type int = number;
type long = number;
type __ERROR_TYPE_NOT_HANDLED__ = number;

// Settings...

export namespace LivestockTradingAPI {

	export namespace Enums {

		export enum XSortingDirection {
			Ascending = 0,
			Descending = 1,
		}

	}

	export namespace Students {

		export namespace Pick {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/Pick';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				selectedIds: Guid[];
				keyword: string;
				limit: number;
			}
			export interface IResponseModel {
				id: Guid;
				name: string;
				studentNumber: string;
			}
		}

		export namespace Detail {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				studentNumber: string;
				firstName: string;
				lastName: string;
				fullName: string;
				email: string;
				phoneNumber: string;
				birthDate?: Date;
				department: string;
				isActive: boolean;
				createdAt: Date;
				updatedAt?: Date;
			}
		}

		export namespace All {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/All';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel[]>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				sorting: IXSorting;
				filters: IXFilterItem[];
				pageRequest: IXPageRequest;
			}
			export interface IXSorting {
				key: string;
				direction: Enums.XSortingDirection;
			}
			export interface IObject {
			}
			export interface IXFilterItem {
				key: string;
				type: string;
				isUsed: boolean;
				values: IObject[];
				min: IObject;
				max: IObject;
				conditionType: string;
			}
			export interface IXPageRequest {
				currentPage: number;
				perPageCount: number;
				listAll: boolean;
			}
			export interface IResponseModel {
				id: Guid;
				studentNumber: string;
				firstName: string;
				lastName: string;
				fullName: string;
				email: string;
				phoneNumber: string;
				birthDate?: Date;
				department: string;
				isActive: boolean;
				createdAt: Date;
			}
		}

		export namespace Update {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/Update';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
				studentNumber: string;
				firstName: string;
				lastName: string;
				email: string;
				phoneNumber: string;
				birthDate?: Date;
				department: string;
				isActive: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace Delete {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/Delete';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				id: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				isDeleted: boolean;
			}
		}

		export namespace Create {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/Create';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				studentNumber: string;
				firstName: string;
				lastName: string;
				email: string;
				phoneNumber: string;
				birthDate?: Date;
				department: string;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

		export namespace LogStudentActivity {
			export const RequestPath = AppConfig.LivestockTradingUrl + '/Students/LogStudentActivity';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				daysToKeep: number;
			}
			export interface IResponseModel {
				processedCount: number;
				processedAt: Date;
				message: string;
			}
		}

	}

}